const ECG_DATABASE = {
    'nsr': { t:"NSR 正常竇性心律", b:"Normal", c:"#4caf50", shock:false, hr:72, sys:120, dia:80, spo2:98, rr:16, temp:37.0, vis:'nsr', cri:["P波存在，節律規則", "PR間期 0.12-0.20s", "心率 60-100 bpm"], patho:"電氣訊號源自竇房結(SA)，經房室結(AV)傳導至心室，路徑完整。", cause:["健康心臟", "休息狀態"], rx:["無需特殊治療"], n:["持續觀察生命徵象"] },
    'sb': { t:"Sinus Bradycardia 竇性緩脈", b:"Brady", c:"#4caf50", shock:false, hr:45, sys:95, dia:60, spo2:96, rr:14, temp:36.8, vis:'sb', cri:["Rate < 60 bpm", "P-QRS-T 波形正常"], patho:"竇房結發火頻率降低，但傳導路徑正常。", cause:["睡眠/運動員", "迷走神經亢進", "藥物 (Beta-blocker)"], rx:["觀察", "有症狀給 Atropine"], n:["監測血壓與意識"] },
    'psvt': { t:"PSVT 室上性心搏過速", b:"Tachy", c:"#ff9800", shock:false, hr:188, sys:90, dia:60, spo2:94, rr:24, temp:37.2, vis:'psvt', cri:["Rate 150-250 bpm", "QRS 窄波", "P波隱藏或倒置"], patho:"房室結折返迴路 (AVNRT) 或房室折返 (AVRT) 形成短路。", cause:["壓力/焦慮/咖啡因", "WPW 症候群"], rx:["Vagal Maneuver", "Adenosine 6mg IVP"], n:["接三通管+抬手", "備妥急救車"] },
    'afib': { t:"Atrial Fibrillation 心房顫動", b:"Irregular", c:"#ff9800", shock:false, hr:130, sys:110, dia:70, spo2:95, rr:20, temp:36.9, vis:'afib', cri:["絕對不規則 (Irregularly Irregular)", "無 P 波 (f waves)", "QRS 通常變窄"], patho:"心房多處微折返亂放電，心房失去收縮功能。", cause:["高血壓", "心衰竭", "瓣膜疾病", "老化"], rx:["心率控制 (Rate Control)", "抗凝血劑 (Anticoagulation)"], n:["監測脈搏缺損", "評估中風風險"] },
    'afl': { t:"Atrial Flutter 心房撲動", b:"Tachy", c:"#ff9800", shock:false, hr:150, sys:110, dia:70, spo2:95, rr:18, temp:37.0, vis:'psvt', cri:["鋸齒狀撲動波 (F waves)", "規則傳導 (如2:1, 3:1)"], patho:"心房內存在單一巨大折返迴路。", cause:["COPD", "肺栓塞", "心臟病"], rx:["心率控制", "同步整流"], n:["監測傳導比例變化"] },
    'pvc': { t:"PVC 心室早期收縮", b:"Ectopic", c:"#ff9800", shock:false, hr:"Irr", sys:115, dia:75, spo2:97, rr:16, temp:37.0, vis:'nsr', cri:["寬大變形 QRS (>0.12s)", "提早出現", "完全代償性暫停"], patho:"心室異位點提早放電，未經正常傳導系統。", cause:["低血鉀/鎂", "缺氧", "咖啡因/酒精"], rx:["觀察", "治療潛在病因", "給予氧氣"], n:["監測出現頻率", "有無成對(Couplet)"] },
    'vt': { t:"VT (Pulse) 心室頻脈", b:"Emergency", c:"#f44336", shock:false, hr:170, sys:90, dia:50, spo2:92, rr:26, temp:37.0, vis:'vt', cri:["寬大 QRS", "規則快速 (>100 bpm)", "單型性或多型性"], patho:"心室折返或異位點主導。心室填充時間不足導致輸出量下降。", cause:["心肌梗塞(MI)", "電解質異常", "藥物中毒"], rx:["Amiodarone", "同步整流 (有脈搏不穩定)"], n:["立即摸脈搏！", "12導程心電圖"] },
    'pvt': { t:"pVT (No Pulse) 無脈性VT", b:"Arrest", c:"#f44336", shock:true, hr:180, sys:"---", dia:"---", spo2:"?", rr:0, temp:36.5, vis:'vt', cri:["同 VT 但無脈搏"], patho:"心室快速跳動但無效收縮，心輸出量為零。", cause:["同 VT (Hs & Ts)"], rx:["去顫電擊 (Defibrillation)", "CPR"], n:["啟動 Code Blue", "高品質 CPR"] },
    'vf': { t:"VF 心室顫動", b:"Arrest", c:"#f44336", shock:true, hr:"---", sys:"---", dia:"---", spo2:"?", rr:0, temp:36.5, vis:'vf', cri:["波形混亂不規則", "無法辨識 QRS", "無脈搏"], patho:"心室肌纖維不協調顫動，無機械收縮功能。", cause:["急性 MI", "R-on-T 現象", "未治療的 VT"], rx:["立即電擊", "CPR", "Epinephrine"], n:["清場 (Clear) 電擊", "減少壓胸中斷"] },
    'tdp': { t:"Torsades de Pointes", b:"Arrest", c:"#f44336", shock:true, hr:220, sys:"---", dia:"---", spo2:"?", rr:0, temp:36.5, vis:'tdp', cri:["多型性 VT", "QRS 波幅像緞帶般扭轉", "QT 延長"], patho:"再極化異常 (R-on-T)，常伴隨長 QT。", cause:["低血鎂", "抗心律不整藥物", "先天性長 QT"], rx:["給予鎂離子 (Magnesium)", "去顫 (若無脈搏)"], n:["備鎂離子 IV", "監測 QT 間期"] },
    'avb1': { t:"1st Degree AVB 一度房室阻滯", b:"Block", c:"#9c27b0", shock:false, hr:70, sys:118, dia:76, spo2:98, rr:16, temp:37.0, vis:'avb1', cri:["PR Interval > 0.20s 固定", "每個 P 都有 QRS"], patho:"房室結傳導延遲，但所有訊號皆傳下。", cause:["藥物 (Digoxin, Beta-blocker)", "迷走神經亢進"], rx:["持續觀察", "調整藥物"], n:["監測是否惡化"] },
    'avb2t1': { t:"2nd Degree Type I (Wenckebach)", b:"Block", c:"#9c27b0", shock:false, hr:60, sys:110, dia:70, spo2:97, rr:16, temp:37.0, vis:'avb1', cri:["PR 逐漸延長直到漏跳 QRS", "循環重複"], patho:"房室結疲勞現象，傳導時間逐次遞增。", cause:["下壁 MI", "藥物副作用"], rx:["觀察", "如有症狀給 Atropine"], n:["備用經皮節律器"] },
    'avb2t2': { t:"2nd Degree Type II", b:"Danger", c:"#9c27b0", shock:false, hr:50, sys:100, dia:60, spo2:95, rr:18, temp:36.8, vis:'avb1', cri:["PR 固定 (正常或延長)", "突然漏跳 QRS"], patho:"希氏束或束支系統病變，容易進展為完全阻滯。", cause:["前壁 MI", "傳導系統退化"], rx:["經皮/經靜脈節律器 (TCP/TVP)"], n:["隨時準備 CPR", "貼上 Pacing Pads"] },
    'avb3': { t:"3rd Degree AVB 完全房室阻滯", b:"Critical", c:"#9c27b0", shock:false, hr:35, sys:80, dia:40, spo2:90, rr:12, temp:36.5, vis:'avb3', cri:["P波與QRS互不相干 (房室分離)", "PP規則，RR規則"], patho:"房室傳導完全中斷，心室由過慢的脫溢節律驅動。", cause:["嚴重 MI", "退化性疾病", "Lyme Disease"], rx:["心臟節律器 (Pacemaker)"], n:["絕對臥床", "防跌倒"] },
    'pea': { t:"PEA 無脈性電活動", b:"Arrest", c:"#f44336", shock:false, hr:70, sys:"---", dia:"---", spo2:"?", rr:0, temp:36.5, vis:'pea', cri:["ECG 有組織波形", "但【無脈搏】"], patho:"電氣功能正常但機械收縮衰竭 (幫浦空轉)。", cause:["5H5T (低血容、缺氧、張力性氣胸...)", "酸中毒"], rx:["CPR", "Epinephrine", "找出並治療原因"], n:["確認導程與脈搏一致性"] },
    'asystole': { t:"Asystole 心律停止", b:"Arrest", c:"#f44336", shock:false, hr:0, sys:"---", dia:"---", spo2:"?", rr:0, temp:36.0, vis:'asystole', cri:["一直線 (Flat line)", "無電氣活動"], patho:"心臟電氣與機械活動完全停止。", cause:["缺氧末期", "死亡"], rx:["CPR", "Epinephrine", "不可電擊"], n:["確認至少兩個導程 (Leads)"] }
};
